services:
  app:
    image: php:8.3-fpm
    container_name: bet_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - devnet

  web:
    image: nginx:alpine
    container_name: bet_web
    ports:
      - "8006:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - devnet

  vite:
    image: node:20-alpine
    container_name: bet_vite
    working_dir: /var/www/html
    ports:
      - "5177:5177"
    volumes:
      - ./:/var/www/html
    command: sh -lc "npm install && npm run dev"
    networks:
      - devnet

  redis:
    image: redis:alpine
    container_name: bet_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - devnet

networks:
  devnet:
    driver: bridge

volumes:
  redis_data: